language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: 87f79c7a3404324e0a7d54d97fe98f3a7e2f09e7a9e8e91050999bc9cf675103
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
  on:
    tags: true
    branches: true
